const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Maputo/manica";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "258867796112" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "258867796112";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "true"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "Alex service",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_05_18_09_08_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICAyMjgsXG4gICAgICAgIDIsXG4gICAgICAgIDExNyxcbiAgICAgICAgMTI2LFxuICAgICAgICAxMTIsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTY3LFxuICAgICAgICAxODQsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMixcbiAgICAgICAgMjI3LFxuICAgICAgICAyMzksXG4gICAgICAgIDI0MyxcbiAgICAgICAgNjEsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjMsXG4gICAgICAgIDIwNSxcbiAgICAgICAgNzQsXG4gICAgICAgIDM0LFxuICAgICAgICA5OSxcbiAgICAgICAgMTAsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTA2LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE2MyxcbiAgICAgICAgNTUsXG4gICAgICAgIDE1MyxcbiAgICAgICAgNyxcbiAgICAgICAgODYsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTA1XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDM0LFxuICAgICAgICA1OSxcbiAgICAgICAgOTQsXG4gICAgICAgIDc0LFxuICAgICAgICA5MixcbiAgICAgICAgMjI0LFxuICAgICAgICA1NSxcbiAgICAgICAgMTgwLFxuICAgICAgICAxODksXG4gICAgICAgIDk3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDIzNyxcbiAgICAgICAgNDksXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTc3LFxuICAgICAgICA3MCxcbiAgICAgICAgMjAyLFxuICAgICAgICAxOTYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjE2LFxuICAgICAgICAzNixcbiAgICAgICAgMjUyLFxuICAgICAgICA1MSxcbiAgICAgICAgODAsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTA2LFxuICAgICAgICAyOSxcbiAgICAgICAgMTYzLFxuICAgICAgICAzOCxcbiAgICAgICAgMTI3LFxuICAgICAgICAxNTAsXG4gICAgICAgIDIyXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTIsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTY3LFxuICAgICAgICA4MSxcbiAgICAgICAgNTQsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjQzLFxuICAgICAgICA4NixcbiAgICAgICAgMzgsXG4gICAgICAgIDE4NyxcbiAgICAgICAgOTQsXG4gICAgICAgIDYsXG4gICAgICAgIDE1OCxcbiAgICAgICAgNzUsXG4gICAgICAgIDEyMixcbiAgICAgICAgOTAsXG4gICAgICAgIDQyLFxuICAgICAgICAyMDAsXG4gICAgICAgIDQyLFxuICAgICAgICA2MCxcbiAgICAgICAgMTY5LFxuICAgICAgICAxNDgsXG4gICAgICAgIDIxLFxuICAgICAgICAxOTMsXG4gICAgICAgIDk5LFxuICAgICAgICAxLFxuICAgICAgICAxNjgsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMTgsXG4gICAgICAgIDE2NyxcbiAgICAgICAgNzdcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjcsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTkyLFxuICAgICAgICAyNTQsXG4gICAgICAgIDU4LFxuICAgICAgICAyMDQsXG4gICAgICAgIDUzLFxuICAgICAgICAxOTMsXG4gICAgICAgIDM3LFxuICAgICAgICAxOCxcbiAgICAgICAgMjEsXG4gICAgICAgIDE3LFxuICAgICAgICA0OCxcbiAgICAgICAgODksXG4gICAgICAgIDY3LFxuICAgICAgICAyNTQsXG4gICAgICAgIDk2LFxuICAgICAgICAxNTAsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMCxcbiAgICAgICAgMjgsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjE1LFxuICAgICAgICA2LFxuICAgICAgICAyMzksXG4gICAgICAgIDE5MixcbiAgICAgICAgOTIsXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjA4LFxuICAgICAgICAxNzgsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNjVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2MCxcbiAgICAgICAgNjEsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxMjIsXG4gICAgICAgIDE2OSxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMTUsXG4gICAgICAgIDExLFxuICAgICAgICAxOTUsXG4gICAgICAgIDE5MixcbiAgICAgICAgNDEsXG4gICAgICAgIDIxLFxuICAgICAgICAyMzgsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTM3LFxuICAgICAgICAxNjEsXG4gICAgICAgIDIzMixcbiAgICAgICAgMTM0LFxuICAgICAgICA1OSxcbiAgICAgICAgMTQ2LFxuICAgICAgICAyNDksXG4gICAgICAgIDM3LFxuICAgICAgICAxNzMsXG4gICAgICAgIDIzLFxuICAgICAgICA4NyxcbiAgICAgICAgMjI1LFxuICAgICAgICAyOSxcbiAgICAgICAgNTgsXG4gICAgICAgIDE4MixcbiAgICAgICAgMjIyLFxuICAgICAgICAxMTJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTAyLFxuICAgICAgICAyMDIsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTQ2LFxuICAgICAgICAyMTMsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNTYsXG4gICAgICAgIDU4LFxuICAgICAgICAyMzcsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMTQxLFxuICAgICAgICAxOTIsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTYzLFxuICAgICAgICAyMTksXG4gICAgICAgIDE3MyxcbiAgICAgICAgMjgsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTQxLFxuICAgICAgICAxMixcbiAgICAgICAgNDAsXG4gICAgICAgIDE1NSxcbiAgICAgICAgNDgsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjcsXG4gICAgICAgIDIyLFxuICAgICAgICAxOTAsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjA1LFxuICAgICAgICA0NixcbiAgICAgICAgOTMsXG4gICAgICAgIDY3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxNTEsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDI1MixcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjE0LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxNjcsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDIzNCxcbiAgICAgICAgICAxMTQsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICAxNTIsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDExMixcbiAgICAgICAgICAxMDEsXG4gICAgICAgICAgMTM4LFxuICAgICAgICAgIDQzLFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICA3OVxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE0NyxcbiAgICAgICAgICAyMixcbiAgICAgICAgICA5MyxcbiAgICAgICAgICAyNTEsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICA2LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxMDcsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxNjksXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAyNDUsXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyOFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE2NSxcbiAgICAgICAgODcsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjMsXG4gICAgICAgIDksXG4gICAgICAgIDgxLFxuICAgICAgICAxOTksXG4gICAgICAgIDUsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTAzLFxuICAgICAgICAzMCxcbiAgICAgICAgNDksXG4gICAgICAgIDEwNSxcbiAgICAgICAgMTIsXG4gICAgICAgIDAsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMzEsXG4gICAgICAgIDgwLFxuICAgICAgICAyMjIsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTI3LFxuICAgICAgICAxNzIsXG4gICAgICAgIDM1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE4LFxuICAgICAgICAxOTEsXG4gICAgICAgIDE5LFxuICAgICAgICAyMzcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNTIsXG4gICAgICAgIDIzNyxcbiAgICAgICAgNzIsXG4gICAgICAgIDg5LFxuICAgICAgICA1MixcbiAgICAgICAgMTk1LFxuICAgICAgICA3MCxcbiAgICAgICAgMjAwLFxuICAgICAgICA2MSxcbiAgICAgICAgMjIsXG4gICAgICAgIDUxLFxuICAgICAgICAxMTcsXG4gICAgICAgIDUzLFxuICAgICAgICAxNTksXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTg2LFxuICAgICAgICAyMjUsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjcsXG4gICAgICAgIDk5LFxuICAgICAgICAxOTgsXG4gICAgICAgIDY5LFxuICAgICAgICAxNDIsXG4gICAgICAgIDI4LFxuICAgICAgICAyMjUsXG4gICAgICAgIDkxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMjE2LFxuICAgICAgICA0MixcbiAgICAgICAgNjMsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjAzLFxuICAgICAgICAyMzYsXG4gICAgICAgIDVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDU5LFxuICBcImFkdlNlY3JldEtleVwiOiBcImNpVHJOdjN1bVVqZjhDQi9kTEg5OEx3U2EzdlNsenkwV0doaXIvdDhiR0U9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU4ODY3Nzk2MTEyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI5RUI0MzcxOTMxRTYyNDVGOTY4MkU5NUVDODdFMjAxQlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjU3NzI2ODZcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCIyNTg4Njc3OTYxMTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjU1NDQ1RUU1OTM1MjJERUQzQjM5NzgxNzAyMkEyM0QzXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyNTc3MjY4NlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjI1ODg2Nzc5NjExMkBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMzI0NDZCRjFGNzBBRDZDNDkzNEUzOTE5RDYyMUIxNkVcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI1NzcyNjg5XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjU4ODY3Nzk2MTEyQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI0QzRFRDEzRTBBNUU5MjQ0NEUwMEQ2MTkzQUVCQTA4NVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjU3NzI2ODlcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiLVdmWWxpZjBRWVNiZHEtcmlETzlQUVwiLFxuICBcInBob25lSWRcIjogXCIzMmQ0NGI2Ni05MWU0LTRlMmUtOTBjMy01ZjkzMjc5MjcwOWFcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMCxcbiAgICAgIDIxMSxcbiAgICAgIDc3LFxuICAgICAgMjAzLFxuICAgICAgNDQsXG4gICAgICAyNSxcbiAgICAgIDUxLFxuICAgICAgNTksXG4gICAgICA3LFxuICAgICAgMTU3LFxuICAgICAgMCxcbiAgICAgIDE1MSxcbiAgICAgIDEzMSxcbiAgICAgIDEwNSxcbiAgICAgIDIxOCxcbiAgICAgIDIwOCxcbiAgICAgIDg0LFxuICAgICAgOTgsXG4gICAgICA4LFxuICAgICAgMjAxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE2LFxuICAgICAgMTc1LFxuICAgICAgMTIyLFxuICAgICAgMTQ0LFxuICAgICAgMTU3LFxuICAgICAgMjI1LFxuICAgICAgMjQwLFxuICAgICAgOTIsXG4gICAgICA2MCxcbiAgICAgIDIxLFxuICAgICAgMjM5LFxuICAgICAgMTc2LFxuICAgICAgMyxcbiAgICAgIDg5LFxuICAgICAgNjksXG4gICAgICAxNjgsXG4gICAgICAyMDYsXG4gICAgICAxMDIsXG4gICAgICA5MixcbiAgICAgIDE5NVxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwicGFpcmluZ0NvZGVcIjogXCI5NU0zTTc0TVwiLFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjU4ODY3Nzk2MTEyOjEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyMjU1NDY0NjYyMzQ1MzE6MTNAbGlkXCIsXG4gICAgXCJuYW1lXCI6IFwiTGNcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNPNlV6WThHRUlqbjlMWUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIktrbTRFUDQ2RTgvbEpXVXMwNjlmRVViZVptdmNzdEZkNDh3RE1nRnpMalU9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiSGM1YVRHMU1mbHZXdkFCSWUzRUxUT1l5LzhtT2tacFEzcW9nam5Bc1h1ZWgrajBCbG1tei8xNm1Tb09wWnRRNStDakpCMnVUM1UrYk85amFTTmlPREE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiREZ5aTZmMXp4RStyUlRSalh0S3lsMFdpeGg5SjkrWmVSOUE4Z3k1UE4xSzZ3aThDMWVkd25McS9ERWl4TWhlUk95dzhtenhtZWNnd2JUSlBubnRQQUE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjU4ODY3Nzk2MTEyOjEzQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgNDIsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICA1OCxcbiAgICAgICAgICAxOSxcbiAgICAgICAgICAyMDcsXG4gICAgICAgICAgMjI5LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICA0NCxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMTc1LFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDIyMixcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDIyMCxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMjA5LFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAyMDQsXG4gICAgICAgICAgMyxcbiAgICAgICAgICA1MCxcbiAgICAgICAgICAxLFxuICAgICAgICAgIDExNSxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA1M1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzI1NzcyNjg0LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBSVI1XCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFJUjUuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJOSjdOVWk4TUVPakZIMFFqN21pTkhvK083UU1yL3h2VXZrSERnSGVicUtzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE2NDMzMzQyNTQsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyNTc3MjY4NDcxNVwifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "public",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
